attributeRules:
- include: 
    uid: ToSic.Eav.DataSources.VisualQuery.VisualQueryAttribute
    type: Type
    type: Class
    type: Interface
    type: Namespace
    type: Member
    type: Method
    type: Property
    
apiRules:
# Exclude System.Object to avoid having .Equals and stuff
# in the documentation
- exclude:
    uidRegex: ^System\.Object

- exclude:
    uidRegex: ^System\.Attribute

- exclude:
    uidRegex: ^System\.IDisposable$

- exclude:
    uidRegex: ^System\.Web
    # includes System.Web.WebPages and System.Web.ApiController

- exclude:
    uidRegex: ^DotNetNuke\.
    # hides things like DotNetNuke.Web.Api.DnnApiController etc.


# Exclude any tests
- exclude:
    uidRegex: ^Tests

# Exclude the everything with the old 2SexyContent namespace
# As this is old and must first be converted to Sxc. before releasing it for official use
- exclude:
    uidRegex: ^ToSic\.SexyContent.*

# maybe do include first, before excludes?
- include:
    hasAttribute: 
        uid: ToSic.Eav.Documentation.PublicApi
- exclude:
    uidRegex: ^ToSic
    type: Member
    type: Namespace
    type: Type
- exclude:
    hasAttribute: 
        uid: ToSic.Eav.Documentation.PrivateApi
    type: Type
    type: Member




attributeRules:
- include: 
    # uidRegex: '^ToSic\.Eav\..*$'
    uid: ToSic.Eav.DataSources.VisualQuery.VisualQueryAttribute
    type: Type
    type: Class
    type: Interface
    type: Namespace
    type: Member
    type: Method
    type: Property
    